import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// Machine-local, uncommitted config (secrets, signing) is read from
// local.properties. The Web client ID (Credential Manager sign-in) becomes a
// BuildConfig field; the RELEASE_* values configure release signing.
val localProperties = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}
val webClientId: String = localProperties.getProperty("WEB_CLIENT_ID", "1050502217992-8au5hrcl0uuu4odfm9bftfll39q6cffs.apps.googleusercontent.com")
val geminiKey: String = localProperties.getProperty("gemini.api.key", "")
val firebaseApiKey: String = localProperties.getProperty("FIREBASE_API_KEY", "AIzaSyDOrjBmSwJ1EP3BtDo6RXgVM8VwScNpi-Q")

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.firebase.crashlytics)
    alias(libs.plugins.firebase.appdistribution)
}

android {
    namespace = "com.dariusepure.caractivitylog"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.dariusepure.caractivitylog"
        minSdk = 26
        targetSdk = 36
        versionCode = 16
        versionName = "2.4"

        multiDexEnabled = true

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables { useSupportLibrary = true }
        
        buildConfigField("String", "WEB_CLIENT_ID", "\"$webClientId\"")
        buildConfigField("String", "GEMINI_API_KEY", "\"$geminiKey\"")
        buildConfigField("String", "FIREBASE_API_KEY", "\"$firebaseApiKey\"")
        buildConfigField("String", "RELEASE_SHA1", "\"67615688F76E557769CAB626F4F20C81B8749483\"")
        buildConfigField("String", "DEBUG_SHA1", "\"C10C6DF2FB85FC2373F01DA647F4F40CCB3F685C\"")

        // Firebase identifiers (can be public, but kept here for convenience)
        buildConfigField("String", "FIREBASE_PROJECT_ID", "\"car-activity-log\"")
        buildConfigField("String", "FIREBASE_APPLICATION_ID", "\"1:1050502217992:android:a0e3c2aac85c6d6fd8ecbd\"")
        buildConfigField("String", "FIREBASE_STORAGE_BUCKET", "\"car-activity-log.firebasestorage.app\"")
        buildConfigField("String", "FIREBASE_GCM_SENDER_ID", "\"1050502217992\"")

        // Manually provide the resources usually generated by the google-services plugin
        // This allows us to use keys from local.properties without plugin conflicts or auto-init crashes
        resValue("string", "google_api_key", firebaseApiKey)
        resValue("string", "google_crash_reporting_api_key", firebaseApiKey)
        resValue("string", "default_web_client_id", webClientId)
        resValue("string", "google_app_id", "1:1050502217992:android:a0e3c2aac85c6d6fd8ecbd")
        resValue("string", "project_id", "car-activity-log")
        resValue("string", "gcm_defaultSenderId", "1050502217992")
        resValue("string", "google_storage_bucket", "car-activity-log.firebasestorage.app")
    }

    signingConfigs {
        val keystorePath = localProperties.getProperty("RELEASE_KEYSTORE_PATH")
        val keystorePassword = localProperties.getProperty("RELEASE_KEYSTORE_PASSWORD")
        val keyAlias = localProperties.getProperty("RELEASE_KEYSTORE_ALIAS")
        val keyPassword = localProperties.getProperty("RELEASE_ALIAS_PASSWORD")

        val isSigningConfigured = keystorePath != null &&
                keystorePassword != null &&
                keyAlias != null &&
                keyPassword != null &&
                file(keystorePath).exists()

        if (isSigningConfigured) {
            create("release") {
                storeFile = file(keystorePath)
                storePassword = keystorePassword
                this.keyAlias = keyAlias
                this.keyPassword = keyPassword
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = if (signingConfigs.findByName("release") != null) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
            firebaseAppDistribution {
                appId = "1:1050502217992:android:a0e3c2aac85c6d6fd8ecbd"
                artifactType = "APK"
                groups = "internal-testers"
                releaseNotes = "Auto Analytics"
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
        buildConfig = true
        resValues = true
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    // AndroidX core
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.androidx.auth.credentials)
    implementation(libs.androidx.auth.credentials.play)

    // Compose BOM ensures all compose libs use compatible versions
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.fonts)
    implementation(libs.androidx.compose.material3)
    implementation("androidx.compose.material3:material3-window-size-class")
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.googleid)

    // Coroutines
    implementation(libs.kotlinx.coroutines.android)

    // Other
    implementation(libs.kotlinx.serialization)

    // Hilt
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.androidx.hilt.navigation.compose)
    implementation(libs.androidx.hilt.work)
    ksp(libs.androidx.hilt.work.compiler)

    // Firebase
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.auth)
    implementation(libs.firebase.firestore)
    implementation(libs.firebase.storage)
    implementation(libs.google.generativeai)
    implementation(libs.firebase.appcheck.playintegrity)
    debugImplementation(libs.firebase.appcheck.debug)
    implementation(libs.firebase.crashlytics)
    implementation(libs.firebase.config)

    // Ktor Dependencies (Forțează importul corect al modulelor)
    val ktorVersion = "2.3.12"
    implementation("io.ktor:ktor-client-core:$ktorVersion")
    implementation("io.ktor:ktor-client-cio:$ktorVersion")
    implementation("io.ktor:ktor-client-android:$ktorVersion")
    implementation("io.ktor:ktor-client-okhttp:$ktorVersion")
    implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-client-logging:$ktorVersion")
    implementation("io.ktor:ktor-client-auth:$ktorVersion")
    implementation("io.ktor:ktor-client-encoding:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")

    // Image loading
    implementation(libs.coil.compose)

    // Room
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    // Charts
    implementation(libs.vico.compose)
    implementation(libs.vico.compose.m3)
    implementation(libs.vico.core)

    // Testing (minimal for the starter, expanded later if needed)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}

// Rezolvare conflict metadate compilator Kotlin cu Hilt / KSP și forțare versiune Ktor
configurations.all {
    resolutionStrategy {
        eachDependency {
            if (requested.group == "io.ktor") {
                // Forțează utilizarea versiunii stabile compatibile cu Gemini
                useVersion("2.3.12")
            }
        }
    }
}
